final imageList = [
  'assets/images/25_commune/Battambang.jpg',
  'assets/images/25_commune/PhnomPenh.jpg',
  'assets/images/25_commune/Bonteaymeanchey.jpg',
  'assets/images/25_commune/KamponChnang.jpg',
  'assets/images/25_commune/KampongThom.jpg',
  'assets/images/25_commune/Kandal.jpg',
  'assets/images/25_commune/kampot.jpg',
  'assets/images/25_commune/Kep.jpg',
  'assets/images/25_commune/Kracheh.jpg',
  'assets/images/25_commune/Oudormeanchey.jpg',
  'assets/images/25_commune/Preah_Vihea.jpg',
  'assets/images/25_commune/PreyVeng.jpeg',
  'assets/images/25_commune/Rathanakiri.jpg',
  'assets/images/25_commune/Siehanuk.jpg',
  'assets/images/25_commune/Siemreab.jpg',
  'assets/images/25_commune/Steng_Treng.jpg',
  'assets/images/25_commune/SvangRieng.jpg',
  'assets/images/25_commune/takao.jpg',
  'assets/images/25_commune/tbongKhmom.jpeg',
  'assets/images/25_commune/Pursat.jpg',
  'assets/images/25_commune/Pailin.jpg',
  'assets/images/25_commune/munduolmiri.jpg',
  'assets/images/25_commune/Kohkong.jpg',
  'assets/images/25_commune/Kampong_Cham.jpg',
  'assets/images/25_commune/Kampong_Speu.jpg',
];
final fruitlist = [
  'Battambong',
  'Phnom Penh',
  'Bonteaymeanchey',
  'KamponChnang',
  'KampongThom',
  'Kandal',
  'kam pot',
  'Kep',
  'Kracheh',
  'Oudormeanchey',
  'Preah Vihea',
  'Prey Veng',
  'Rathanakiri',
  'Siehanuk',
  'Siem Reab',
  'Steng Treng',
  'Svang Rieng',
  'Ta kao',
  'TbongKhmom',
  'Pur sat',
  'Pai lin',
  'Mondolkiri',
  'Kohkong',
  'Kampong Cham',
  'Kampong Speu',
];
