List imageIcons = [
  {"icons": "assets/icons/house2.png"},
  {"icons": "assets/icons/lot.png"},
  {"icons": "assets/icons/parking.png"},
  {"icons": "assets/icons/bed.png"},
  {"icons": "assets/icons/Size.png"},
  {"icons": "assets/icons/floor.png"},
  {"icons": "assets/icons/ice.png"},
  {"icons": "assets/icons/bath.png"},
  {"icons": "assets/icons/area.png"},
  {"icons": "assets/icons/living_room.png"},
  {"icons": "assets/icons/total_area.png"},
];
List titleName = [
  {"title": "hometype"},
  {"title": "lot(sqm)"},
  {"title": "parking"},
  {"title": "Bed"},
  {"title": "price_sqm"},
  {"title": "Size(sqm)"},
  {"title": "Floor"},
  {"title": "Aircon"},
  {"title": "bath"},
  {"title": "Private_Area"},
  {"title": "TotalArea"},
];
List listValue = [
  {"value": "type"},
  {"value": "land"},
  {"value": "bed"},
  {"value": "price_sqm"},
  {"value": "sqm"},
  {"value": "floor"},
  {"value": "aircon"},
  {"value": "bath"},
  {"value": "Private_Area"},
  {"value": "Livingroom"},
  {"value": "total_area"},
];
